version: '3.8'
services:
  scraper:
    build: .
    container_name: webscraping_hub
    volumes:
      - ./amz_auth.json:/app/amz_auth.json
      - ./meli_auth.json:/app/meli_auth.json
    environment:
      - API_URL=https://www.price.kamico.com.br/api/products
    # Se quiser rodar outro script, altere o comando abaixo
    command: ["python", "execucao.py"] 