import time
import asyncio
import requests
from datetime import datetime
from scrape_combined_crawl4ai import process_urls, carregar_sem_dados_url
import re

async def run_combined_crawler():
    print(f'Executando scrape_combined_crawl4ai.py às {datetime.now()}')
    try:
        # Lista de URLs ajustada no formato de dicionários com 'url' e 'sku'
        combined_urls = [
            {
                "url": "https://www.belezanaweb.com.br/kit-wella-professionals-invigo-nutrienrich-salon-duo-treatment-mask-2-produtos/ofertas-marketplace",
                "sku": "WLK005blz"
            },
            {
                "url": "https://www.belezanaweb.com.br/kit-wella-professionals-invigo-nutrienrich-super-salon-2-produtos/ofertas-marketplace",
                "sku": "WLK005blz"
            },
            {"url": "https://www.belezanaweb.com.br/kit-wella-professionals-nutrienrich-absolute-salon-dueto-2-produtos/ofertas-marketplace", "sku": "WLK004blz"},
            {"url": "https://www.belezanaweb.com.br/kit-wella-professionals-invigo-nutrienrich-salon-dueto-2-produtos/ofertas-marketplace", "sku": "WLK004blz"},
            {"url": "https://www.epocacosmeticos.com.br/pesquisa?q=4064666306179", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B0BGJ5RB67", "sku": None},
            {"url": "https://www.mercadolivre.com.br/shampoo-wella-invigo-nutri-enrich-1-litro-profissional/p/MLB20570794/s", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07KSDBVJW", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B0DJ1QCJL9", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07KSFWRK7", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B085Z2MYFL", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B01F9ZSZ8O", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B00CZC5F0G", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07KSD84NN", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B076JS1JG5", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B01F9ZSWLY", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07FYV4WK3", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07YD6C2WH", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07LH9F1LX", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B09MNL1QZQ", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B083JT5T7Q", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07LH7ZSWK", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07FZ6PKJF", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B00FAQRKT8", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B0719FDXCP", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B098CF44X7", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B097ZBHF6N", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B085ZB4ZY1", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B06Y2D6KSZ", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B077C3QD52", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B06Y2H832L", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07GKQ3QXH", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07N6NQ53K", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B085YZLF97", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B00JPZAJPM", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B01FVH8Z6W", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B08LHDPVRL", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B085ZJ5CN1", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07V5JJPMY", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07KSGCC6L", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B09X8CZW18", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07M9WGSJJ", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07MG75WL3", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B0C2G5DQV3", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07L6L2YWY", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07Y3YRWCB", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B0C2FX5XV9", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B0BNCBX6NT", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B06Y1YBBMV", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B010EF137O", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B06Y22T1NJ", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B085ZJL7V3", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07V1X42LR", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B0C2FYX26R", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B077BY8NR5", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B077T49BGR", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B00YS699ZY", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B085Z1D33T", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B0CB1SFYTX", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07LH9HCV8", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B0DHLFQXDM", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07MG8G9NB", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B077C475QK", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B09Q5KNWLX", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B0D2PKQVM6", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B09L6WQVW5", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07YCSV7TW", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B09NGP5PBN", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07FV2M2WW", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07N1HWSH2", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B083M7WZBZ", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B08FZLLMZ3", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B09GBFYX9C", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07NVX24DS", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B0DHLFDT2Y", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B0DKY5Q1B8", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B085Z5WKBB", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B085ZKX86Q", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B0BCL4F5RR", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B09ZGTC91G", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B077BY5VN5", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B077C3THHT", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B089T8ZDTL", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B0C2FZ7PT1", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B08DRGMPJ8", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B085ZB4M5Y", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B08X8MTQWF", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07CX97JHH", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B0CFHSXG21", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07NPRBFM4", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07NMF6JRZ", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07NXVWVG2", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07FYLRHXP", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07MBQY7K9", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07MG6ZZDS", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B09X9KDZBB", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07QMZFJD6", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B08LHFS61Z", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B0C2FHH98G", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B01N2UMUA7", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07FV5RLPN", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B0789QCHD4", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B09L6WJ88X", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B083JTTBVK", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B085Z3LPFK", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B08LHDT86K", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B09NQKCRCW", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B08KHQ4TP5", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07FVB39DH", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B086N2Z1VQ", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B089WKYCFF", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07YX3YN4Y", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B000F4GLAY", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B077C3SPXV", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07L6LK238", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07LHGVF3P", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B0BNJT83K6", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B0DKXZTZKV", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B077C5FT38", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B07GWKGMJR", "sku": None},
            {"url": "https://www.amazon.com.br/dp/B082QJ65K8", "sku": None},
            {"url": "https://www.mercadolivre.com.br/shampoo-higienizando-widi-care-a-juba-500ml-limpeza-inteligente/p/MLB19860817/s", "sku": None},
            {"url": "https://www.mercadolivre.com.br/acidificante-widi-care-acidificando-a-juba-500ml/p/MLB36742897/s", "sku": None},
            {"url": "https://www.mercadolivre.com.br/wella-mascara-oil-reflections-500ml/p/MLB19512787/s", "sku": None},
            {"url": "https://www.amazon.com.br/Acidificando-Juba-Acidificante-Widi-500ml/dp/B0D389WN7Z/?_encoding=UTF8&ref_=pd_hp_d_atf_ci_mcx_mr_ca_hp_atf_d", "sku": None},
            {"url": "https://www.amazon.com.br/Widicare-Encaracolando-Juba-Creme-Pentear/dp/B0BGJ5RB67/ref=sr_1_1?rdc=1&s=beauty&sr=1-1", "sku": None},
            {"url": "https://www.mercadolivre.com.br/cadiveu-plastica-dos-fios-selagem-termica-passo-2/p/MLB20549848/s", "sku": None},
            {"url": "https://www.mercadolivre.com.br/wella-mascara-oil-reflections-500ml/p/MLB19512787/s?pdp_filters=item_id%3AMLB4395639466", "sku": None},
            {"url": "https://www.belezanaweb.com.br/wella-professionals-invigo-color-brilliance-shampoo-1-litro/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/wella-professionals-invigo-color-brilliance-condicionador-1-litro/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/wella-professionals-invigo-color-brilliance-mascara-capilar-500ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/wella-professionals-invigo-nutrienrich-shampoo-1-litro/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/wella-professionals-invigo-nutrienrich-condicionador-1-litro/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/wella-professionals-invigo-nutrienrich-mascara-capilar-500ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/wella-professionals-oil-reflections-luminous-reveal-shampoo-1-litro/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/wella-professionals-oil-reflections-luminous-reboost-mascara-500ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/wella-professionals-oil-reflections-oleo-capilar-100ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/wella-professionals-oil-reflections-light-oleo-capilar-100ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-professional-acai-oil-oleo-de-tratamento-60ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/kit-cadiveu-professional-plastica-dos-fios-alinhamento-profissional-3-produtos/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-professional-essentials-bye-bye-frizz-gradual-smoothing-mist-spray-protetor-termico-200ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-essentials-quartzo-shine-by-boca-rosa-hair-oleo-capilar-quartzo-liquido-65ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/deva-curl-one-condition-condicionador-355ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-professional-nutri-glow-mascara-capilar-200ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/deva-curl-heaven-in-hair-mascara-capilar-250g/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/deva-curl-supercream-creme-modelador-250g/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-essentials-quartzo-shine-leavein-protetor-termico-200ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/senscience-inner-restore-intensif-mascara-capilar-de-500ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/senscience-inner-restore-mascara-capilar-500ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/senscience-inner-restore-deep-moisturizing-conditioner-mascara-200ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/senscience-cpr-step-3-condicionador-1l/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/widi-care-condicionando-a-juba-hidronutritivo-condicionador-500ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/widi-care-ondulando-a-juba-creme-de-pentear-500ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/widi-care-modelando-a-juba-geleia-seladora-300g/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/widi-care-encrespando-a-juba-creme-de-pentear-500ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/widi-care-juba-mascara-capilar-500g/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/joico-moisture-recovery-moisturizing-smart-release-shampoo-1l/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/joico-kpak-to-repair-damage-hair-smart-release-shampoo-300ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/deva-curl-supercream-creme-modelador-500g/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/deva-curl-one-condition-decadence-condicionador-355ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-essentials-quartzo-shine-proteina-condicionante-preshampoo-200ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-profissional-glamour-essentials-serum-capilar-65ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-professional-nutri-glow-leavein-nutritivo-215ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-professional-glamour-essentials-fluido-condicionante-200ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/kit-cadiveu-professional-essentials-hair-remedy-home-care-3-produtos/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-professional-nutri-glow-shampoo-250ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-professional-acai-oil-oleo-de-acai-110ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/widi-care-cabeleira-crescimento-e-fortalecimento-fluido-fortificante-120ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/kit-homecare-cadiveu-essentials-quartzo-shine-2-produtos/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/aneethun-linha-a-mascara-capilar-500g/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/deva-curl-styling-cream-creme-modelador-500g/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/brae-divine-antifrizz-condicionador-1l/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/senscience-silk-moisture-condicionador-240ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-professional-essentials-maxi-ondas-leavein-200ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/wella-professionals-invigo-nutrienrich-warming-express-mascara-de-nutricao-150ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-essentials-quartzo-shine-shampoo-250ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/deva-curl-angell-leave-in-355ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-professional-repair-solution-mascara-reparadora-200ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-essentials-quartzo-shine-mascara-de-tratamento-200ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/deva-curl-no-poo-shampoo-cremoso-355ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/deva-curl-heaven-in-hair-mascara-capilar-500g/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/aneethun-linha-a-silicone-com-tutano-e-queratina-creme-capilar-250ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/deva-curl-original-shampoo-nopoo-1l/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-essentials-quartzo-shine-balm-leavein-120ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-professional-nutri-glow-leavein-150ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/deva-curl-low-poo-deligh-shampoo-355ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/deva-curl-no-poo-decadence-shampoo-sem-espuma-355ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/brae-stages-nutrition-shampoo-250ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/deva-curl-one-condition-delight-condicionador-355ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/brae-essential-power-dose-ampola-de-tratamento-capilar-13ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-professional-repair-solution-leavein-reparador-215ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-professional-repair-solution-sem-sulfato-shampoo-reparador-250ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/deva-curl-care-angell-modelador-120ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/widi-care-blend-de-oleos-vegetais-tratamento-capilar-60ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/deva-curl-angell-leavein-1l/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-essentials-quartzo-shine-condicionador-250ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/brae-go-curly-leavein-200ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-professional-essentials-bye-bye-frizz-shampoo-shampoo-250ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/kit-cadiveu-professional-glamour-essentials-home-care-2-produtos/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-professional-repair-solution-condicionador-reparador-250ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/brae-go-curly-mascara-capilar-200g/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/prohall-cosmetic-btx-blend-repair-tratamento-disciplinante-300g/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/brae-divine-antifrizz-shampoo-1000ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/brae-stages-treatment-leavein-multifuncional-em-spray-260ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/joico-moisture-recovery-smart-release-condicionador-250ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/brae-stage-hydration-mascara-capilar-200g/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-professional-essentials-bye-bye-frizz-mask-mascara-capilar-condicionadora-200ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-essentials-bye-bye-frizz-killer-leave-in-120ml", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-professional-glamour-essentials-mascara-capilar-200ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-professional-nutri-glow-condicionador-250ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/deva-curl-shampoo-low-poo-1l/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/brae-divine-condicionador-250ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-professional-essentials-bye-bye-frizz-conditioner-condicionador-250ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/aneethun-linha-a-shampoo-300ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/deva-curl-styling-cream-creme-de-pentear-250g/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/jacques-janine-professionnel-bb-cream-finalizador-240ml", "sku": None},
            {"url": "https://www.belezanaweb.com.br/jacques-janine-professionnel-liso-absoluto-fluido-termoativado-120ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/brae-bond-angel-blonde-repair-mascara-capilar-200g/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-professional-essentials-hair-remedy-leavein-condicionante-120ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/joico-kpak-to-repair-damage-hair-smart-release-condicionador-250ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/brae-beach-hair-day-finalizador-capilar-260ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/deva-curl-delight-shampoo-low-poo-1l/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/brae-bond-angel-thermal-blond-leavein-matizador-200ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/brae-stagesnutrition-condicionador-250-ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/kit-cadiveu-professional-plastica-dos-fios-2-produtos/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/brae-essential-fluido-reparador-leavein-60ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/deva-curl-one-condition-decadence-condicionador-1l/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/aneethun-repair-system-mascara-posquimica-250g/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/brae-revival-condicionador-250ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/deva-curl-decadence-shampoo-no-poo-1l/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/wella-professionals-invigo-color-brilliance-shampoo-250ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/brae-fiber-mask-efeito-teia-mascara-capilar-500g/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-professional-glamour-essentials-shampoo-250ml", "sku": None},
            {"url": "https://www.belezanaweb.com.br/brae-divine-home-care-mascara-capilar-200g/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/wella-professionals-fusion-shampoo-1000ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/wella-professionals-fusion-condicionador-1-litro/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/wella-professionals-fusion-mascara-reparadora-500ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/senscience-cpr-step-0-shampoo-1l/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/senscience-silk-moisture-shampoo-1l/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/senscience-silk-moisture-shampoo-280ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/senscience-balance-condicionador-240ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/senscience-true-hue-color-serum-capilar-55ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/senscience-balance-shampoo-280ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/senscience-smooth-shampoo-1000ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/senscience-silk-moisture-condicionador-1l/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/joico-joifull-volumizing-smart-release-leavein-100ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/wella-professionals-color-motion-condicionador-1000ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/joico-blonde-life-brilliant-glow-brightening-oil-oleo-capilar-100ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/mp293269-mascara-cabelos-loiros-brae-stages-blonding-200g/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/brae-shampoo-stages-blonding-250ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/mp293272-mascara-cabelos-coloridos-brae-stages-color-protect-200g", "sku": None},
            {"url": "https://www.belezanaweb.com.br/brae-stages-colors-protect-shampoo-250ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/brae-stage-hydration-shampoo-250ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-professional-final-style-extra-shine-spray-de-brilho-150ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/senscience-true-hue-shampoo-sem-sulfato-280ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/senscience-inner-restore-deep-moisturizing-mascara-de-hidratacao-50ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/senscience-true-hue-condicionador-1l/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/senscience-cpr-step-1-porosity-reconstructor-tratamento-reconstrutor1l/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-blonde-reconstructor-ph-balancing-mask-mascara-capilar-1l/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-professional-soft-sense-condicionador-3l/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-professional-hair-remedy-condicionador-980ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-professional-nutri-glow-mascara-capilar-980ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-professional-nutri-glow-condicionador-980ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/cadiveu-professional-nutri-glow-shampoo-980ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/deva-curl-wave-maker-ativador-de-cachos-180ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/deva-curl-mist-er-right-finalizador-120ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/deva-curl-b-leavein-finalizador-condicionante-200ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/deva-curl-b-leavein-120ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/deva-curl-set-it-free-finalizador-120ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/deva-curl-one-condition-delight-condicionador-1l/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/deva-curl-low-poo-shampoo-355ml/ofertas-marketplace", "sku": None},
            {"url": "https://www.belezanaweb.com.br/senscience-cpr-step-3-condicionador-1l/ofertas-marketplace", "sku": None}
        ]

        # Remove duplicatas com base no campo 'url', mantendo a primeira ocorrência
        seen_urls = set()
        unique_urls = []
        for url_data in combined_urls:
            url = url_data.get('url')
            if url not in seen_urls:
                seen_urls.add(url)
                unique_urls.append(url_data)

        print(f'Total de URLs únicas a processar: {len(unique_urls)}')
        await process_urls(unique_urls)
    except Exception as e:
        print(f'Erro ao executar scrape_combined_crawl4ai.py: {e}')

if __name__ == '__main__':
    asyncio.run(run_combined_crawler())