

import time
import asyncio
import requests
from datetime import datetime
from scrape_combined_crawl4ai import process_urls, carregar_sem_dados_url
import re

async def run_combined_crawler():
    print(f'Executando scrape_combined_crawl4ai.py às {datetime.now()}')
    try:
        combined_urls = [
            "https://www.amazon.com.br/dp/B07KSDBVJW",
            "https://www.amazon.com.br/dp/B0933L5RJC",
            "https://www.amazon.com.br/dp/B0DJ1QCJL9",
            "https://www.amazon.com.br/dp/B07KSFWRK7",
            "https://www.amazon.com.br/dp/B085Z2MYFL",
            "https://www.amazon.com.br/dp/B01F9ZSZ8O",
            "https://www.amazon.com.br/dp/B00CZC5F0G",
            "https://www.amazon.com.br/dp/B07KSD84NN",
            "https://www.amazon.com.br/dp/B076JS1JG5",
            "https://www.amazon.com.br/dp/B01F9ZSWLY",
            "https://www.amazon.com.br/dp/B07FYV4WK3",
            "https://www.amazon.com.br/dp/B07KSDBVJW",
            "https://www.amazon.com.br/dp/B07YD6C2WH",
            "https://www.amazon.com.br/dp/B07LH9F1LX",
            "https://www.amazon.com.br/dp/B09MNL1QZQ",
            "https://www.amazon.com.br/dp/B083JT5T7Q",
            "https://www.amazon.com.br/dp/B07LH7ZSWK",
            "https://www.amazon.com.br/dp/B07FZ6PKJF",
            "https://www.amazon.com.br/dp/B00FAQRKT8",
            "https://www.amazon.com.br/dp/B0719FDXCP",
            "https://www.amazon.com.br/dp/B098CF44X7",
            "https://www.amazon.com.br/dp/B097ZBHF6N",
            "https://www.amazon.com.br/dp/B085ZB4ZY1",
            "https://www.amazon.com.br/dp/B06Y2D6KSZ",
            "https://www.amazon.com.br/dp/B077C3QD52",
            "https://www.amazon.com.br/dp/B06Y2H832L",
            "https://www.amazon.com.br/dp/B07GKQ3QXH",
            "https://www.amazon.com.br/dp/B07N6NQ53K",
            "https://www.amazon.com.br/dp/B085YZLF97",
            "https://www.amazon.com.br/dp/B00JPZAJPM",
            "https://www.amazon.com.br/dp/B01FVH8Z6W",
            "https://www.amazon.com.br/dp/B08LHDPVRL",
            "https://www.amazon.com.br/dp/B085ZJ5CN1",
            "https://www.amazon.com.br/dp/B07V5JJPMY",
            "https://www.amazon.com.br/dp/B07KSGCC6L",
            "https://www.amazon.com.br/dp/B09X8CZW18",
            "https://www.amazon.com.br/dp/B07M9WGSJJ",
            "https://www.amazon.com.br/dp/B07MG75WL3",
            "https://www.amazon.com.br/dp/B0C2G5DQV3",
            "https://www.amazon.com.br/dp/B07L6L2YWY",
            "https://www.amazon.com.br/dp/B07Y3YRWCB",
            "https://www.amazon.com.br/dp/B0C2FX5XV9",
            "https://www.amazon.com.br/dp/B0BNCBX6NT",
            "https://www.amazon.com.br/dp/B06Y1YBBMV",
            "https://www.amazon.com.br/dp/B010EF137O",
            "https://www.amazon.com.br/dp/B06Y22T1NJ",
            "https://www.amazon.com.br/dp/B085ZJL7V3",
            "https://www.amazon.com.br/dp/B07V1X42LR",
            "https://www.amazon.com.br/dp/B0C2FYX26R",
            "https://www.amazon.com.br/dp/B077BY8NR5",
            "https://www.amazon.com.br/dp/B077T49BGR",
            "https://www.amazon.com.br/dp/B00YS699ZY",
            "https://www.amazon.com.br/dp/B085Z1D33T",
            "https://www.amazon.com.br/dp/B0CB1SFYTX",
            "https://www.amazon.com.br/dp/B07LH9HCV8",
            "https://www.amazon.com.br/dp/B098CF44X7",
            "https://www.amazon.com.br/dp/B0DHLFQXDM",
            "https://www.amazon.com.br/dp/B07MG8G9NB",
            "https://www.amazon.com.br/dp/B077C475QK",
            "https://www.amazon.com.br/dp/B09Q5KNWLX",
            "https://www.amazon.com.br/dp/B0D2PKQVM6",
            "https://www.amazon.com.br/dp/B0D2PKQVM6",
            "https://www.amazon.com.br/dp/B09L6WQVW5",
            "https://www.amazon.com.br/dp/B07YCSV7TW",
            "https://www.amazon.com.br/dp/B09NGP5PBN",
            "https://www.amazon.com.br/dp/B07FV2M2WW",
            "https://www.amazon.com.br/dp/B07N1HWSH2",
            "https://www.amazon.com.br/dp/B083M7WZBZ",
            "https://www.amazon.com.br/dp/B08FZLLMZ3",
            "https://www.amazon.com.br/dp/B09GBFYX9C",
            "https://www.amazon.com.br/dp/B07NVX24DS",
            "https://www.amazon.com.br/dp/B07YCSV7TW",
            "https://www.amazon.com.br/dp/B0DHLFDT2Y",
            "https://www.amazon.com.br/dp/B0DKY5Q1B8",
            "https://www.amazon.com.br/dp/B085Z5WKBB",
            "https://www.amazon.com.br/dp/B085ZKX86Q",
            "https://www.amazon.com.br/dp/B0BCL4F5RR",
            "https://www.amazon.com.br/dp/B09ZGTC91G",
            "https://www.amazon.com.br/dp/B077BY5VN5",
            "https://www.amazon.com.br/dp/B077C3THHT",
            "https://www.amazon.com.br/dp/B089T8ZDTL",
            "https://www.amazon.com.br/dp/B0C2FZ7PT1",
            "https://www.amazon.com.br/dp/B08DRGMPJ8",
            "https://www.amazon.com.br/dp/B085ZB4M5Y",
            "https://www.amazon.com.br/dp/B08X8MTQWF",
            "https://www.amazon.com.br/dp/B07CX97JHH",
            "https://www.amazon.com.br/dp/B0CFHSXG21",
            "https://www.amazon.com.br/dp/B07NPRBFM4",
            "https://www.amazon.com.br/dp/B07NMF6JRZ",
            "https://www.amazon.com.br/dp/B07NXVWVG2",
            "https://www.amazon.com.br/dp/B07FYLRHXP",
            "https://www.amazon.com.br/dp/B07MBQY7K9",
            "https://www.amazon.com.br/dp/B07MG6ZZDS",
            "https://www.amazon.com.br/dp/B09X9KDZBB",
            "https://www.amazon.com.br/dp/B07QMZFJD6",
            "https://www.amazon.com.br/dp/B08LHFS61Z",
            "https://www.amazon.com.br/dp/B0C2FHH98G",
            "https://www.amazon.com.br/dp/B01N2UMUA7",
            "https://www.amazon.com.br/dp/B07FV5RLPN",
            "https://www.amazon.com.br/dp/B0789QCHD4",
            "https://www.amazon.com.br/dp/B09L6WJ88X",
            "https://www.amazon.com.br/dp/B083JTTBVK",
            "https://www.amazon.com.br/dp/B085Z3LPFK",
            "https://www.amazon.com.br/dp/B08LHDT86K",
            "https://www.amazon.com.br/dp/B09NQKCRCW",
            "https://www.amazon.com.br/dp/B08KHQ4TP5",
            "https://www.amazon.com.br/dp/B07FVB39DH",
            "https://www.amazon.com.br/dp/B086N2Z1VQ",
            "https://www.amazon.com.br/dp/B089WKYCFF",
            "https://www.amazon.com.br/dp/B07YX3YN4Y",
            "https://www.amazon.com.br/dp/B000F4GLAY",
            "https://www.amazon.com.br/dp/B077C3SPXV",
            "https://www.amazon.com.br/dp/B07L6LK238",
            "https://www.amazon.com.br/dp/B085Z2MYFL",
            "https://www.amazon.com.br/dp/B07LHGVF3P",
            "https://www.amazon.com.br/dp/B0BNJT83K6",
            "https://www.amazon.com.br/dp/B0CB1SFYTX",
            "https://www.amazon.com.br/dp/B0DKXZTZKV",
            "https://www.amazon.com.br/dp/B077C5FT38",
            "https://www.amazon.com.br/dp/B07GWKGMJR",
            "https://www.amazon.com.br/dp/B082QJ65K8",
            'https://www.mercadolivre.com.br/shampoo-higienizando-widi-care-a-juba-500ml-limpeza-inteligente/p/MLB19860817/s?',
            'https://www.mercadolivre.com.br/acidificante-widi-care-acidificando-a-juba-500ml/p/MLB36742897/s?',
            'https://www.mercadolivre.com.br/wella-mascara-oil-reflections-500ml/p/MLB19512787/s?'
            'https://www.belezanaweb.com.br/wella-professionals-invigo-color-brilliance-shampoo-1-litro/ofertas-marketplace',
            'https://www.belezanaweb.com.br/wella-professionals-invigo-color-brilliance-condicionador-1-litro/ofertas-marketplace',
            'https://www.belezanaweb.com.br/wella-professionals-invigo-color-brilliance-mascara-capilar-500ml/ofertas-marketplace',
            'https://www.belezanaweb.com.br/wella-professionals-invigo-nutrienrich-shampoo-1-litro/ofertas-marketplace',
            'https://www.belezanaweb.com.br/wella-professionals-invigo-nutrienrich-condicionador-1-litro/ofertas-marketplace',
            'https://www.belezanaweb.com.br/wella-professionals-invigo-nutrienrich-mascara-capilar-500ml/ofertas-marketplace',
            'https://www.belezanaweb.com.br/wella-professionals-oil-reflections-luminous-reveal-shampoo-1-litro/ofertas-marketplace',
            'https://www.belezanaweb.com.br/wella-professionals-oil-reflections-luminous-reboost-mascara-500ml/ofertas-marketplace',
            'https://www.belezanaweb.com.br/wella-professionals-oil-reflections-oleo-capilar-100ml/ofertas-marketplace',
            'https://www.belezanaweb.com.br/wella-professionals-oil-reflections-light-oleo-capilar-100ml/ofertas-marketplace',
            'https://www.mercadolivre.com.br/shampoo-higienizando-widi-care-a-juba-500ml-limpeza-inteligente/p/MLB19860817/s',
            'https://www.amazon.com.br/Acidificando-Juba-Acidificante-Widi-500ml/dp/B0D389WN7Z/?_encoding=UTF8&ref_=pd_hp_d_atf_ci_mcx_mr_ca_hp_atf_d',
            'https://www.amazon.com.br/Widicare-Encaracolando-Juba-Creme-Pentear/dp/B0BGJ5RB67/ref=sr_1_1?rdc=1&s=beauty&sr=1-1',
            # 'https://www.mercadolivre.com.br/cadiveu-plastica-dos-fios-selagem-termica-passo-2/p/MLB20549848/s',
            # 'https://www.mercadolivre.com.br/wella-mascara-oil-reflections-500ml/p/MLB19512787/s?pdp_filters=item_id%3AMLB4395639466',
            'https://www.belezanaweb.com.br/cadiveu-professional-acai-oil-oleo-de-tratamento-60ml/ofertas-marketplace',
            'https://www.belezanaweb.com.br/kit-cadiveu-professional-plastica-dos-fios-alinhamento-profissional-3-produtos/ofertas-marketplace',
            'https://www.belezanaweb.com.br/cadiveu-professional-essentials-bye-bye-frizz-gradual-smoothing-mist-spray-protetor-termico-200ml/ofertas-marketplace',    
            'https://www.belezanaweb.com.br/cadiveu-essentials-quartzo-shine-by-boca-rosa-hair-oleo-capilar-quartzo-liquido-65ml/ofertas-marketplace',
            'https://www.belezanaweb.com.br/deva-curl-one-condition-condicionador-355ml/ofertas-marketplace',
            'https://www.belezanaweb.com.br/cadiveu-professional-nutri-glow-mascara-capilar-200ml/ofertas-marketplace',
            'https://www.belezanaweb.com.br/deva-curl-heaven-in-hair-mascara-capilar-250g/ofertas-marketplace',
            'https://www.belezanaweb.com.br/deva-curl-supercream-creme-modelador-250g/ofertas-marketplace',
            'https://www.belezanaweb.com.br/cadiveu-essentials-quartzo-shine-leavein-protetor-termico-200ml/ofertas-marketplace',
            'https://www.belezanaweb.com.br/senscience-inner-restore-intensif-mascara-capilar-de-500ml/ofertas-marketplace',
            'https://www.belezanaweb.com.br/senscience-inner-restore-mascara-capilar-500ml/ofertas-marketplace',
            'https://www.belezanaweb.com.br/senscience-inner-restore-deep-moisturizing-conditioner-mascara-200ml/ofertas-marketplace',
            'https://www.belezanaweb.com.br/senscience-cpr-step-3-condicionador-1l/ofertas-marketplace',
            'https://www.belezanaweb.com.br/widi-care-condicionando-a-juba-hidronutritivo-condicionador-500ml/ofertas-marketplace',
            'https://www.belezanaweb.com.br/widi-care-ondulando-a-juba-creme-de-pentear-500ml/ofertas-marketplace',
            'https://www.belezanaweb.com.br/widi-care-modelando-a-juba-geleia-seladora-300g/ofertas-marketplace',
            'https://www.belezanaweb.com.br/widi-care-encrespando-a-juba-creme-de-pentear-500ml/ofertas-marketplace',
            'https://www.belezanaweb.com.br/widi-care-juba-mascara-capilar-500g/ofertas-marketplace',
            'https://www.belezanaweb.com.br/joico-moisture-recovery-moisturizing-smart-release-shampoo-1l/ofertas-marketplace',
            'https://www.belezanaweb.com.br/joico-kpak-to-repair-damage-hair-smart-release-shampoo-300ml/ofertas-marketplace',
            'https://www.belezanaweb.com.br/deva-curl-supercream-creme-modelador-500g/ofertas-marketplace',
            'https://www.belezanaweb.com.br/deva-curl-one-condition-decadence-condicionador-355ml/ofertas-marketplace',
            'https://www.belezanaweb.com.br/cadiveu-essentials-quartzo-shine-proteina-condicionante-preshampoo-200ml/ofertas-marketplace',
            'https://www.belezanaweb.com.br/cadiveu-essentials-quartzo-shine-by-boca-rosa-hair-oleo-capilar-quartzo-liquido-65ml/ofertas-marketplace',
            'https://www.belezanaweb.com.br/cadiveu-profissional-glamour-essentials-serum-capilar-65ml/ofertas-marketplace',
            'https://www.belezanaweb.com.br/cadiveu-professional-nutri-glow-leavein-nutritivo-215ml/ofertas-marketplace',
            'www.belezanaweb.com.br/cadiveu-professional-glamour-essentials-fluido-condicionante-200ml/ofertas-marketplace',
            'www.belezanaweb.com.br/kit-cadiveu-professional-essentials-hair-remedy-home-care-3-produtos/ofertas-marketplace',
            'https://www.belezanaweb.com.br/cadiveu-professional-nutri-glow-shampoo-250ml/ofertas-marketplace',
            'https://www.belezanaweb.com.br/cadiveu-professional-acai-oil-oleo-de-tratamento-60ml/ofertas-marketplace',
            'https://www.belezanaweb.com.br/cadiveu-professional-acai-oil-oleo-de-acai-110ml/ofertas-marketplace',
        ]

        # Carrega URLs que falharam anteriormente
        sem_dado = carregar_sem_dados_url()
        
        # Valida URLs para evitar concatenações ou formatos inválidos
        valid_urls = []
        for url in sem_dado + combined_urls:
            if re.match(r'^https?://', url) and ' ' not in url:  # Verifica se é uma URL válida
                valid_urls.append(url)
            else:
                print(f"URL inválida ignorada: {url}")
        
        # Remove duplicatas mantendo a ordem
        combined_urls = list(dict.fromkeys(valid_urls))
        
        await process_urls(combined_urls)
    except Exception as e:
        print(f'Erro ao executar scrape_combined_crawl4ai.py: {e}')

if __name__ == '__main__':
    asyncio.run(run_combined_crawler())


